name: github-actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: cuda-toolkit (Install CUDA)
      uses: Jimver/cuda-toolkit@v0.2.3
    - name: Installed Cuda Version
      run: ${{steps.cuda-toolkit.outputs.cuda}}
    - name: Cuda Install Location
      run: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}
    - name: NVCC
      run: nvcc -V
    - name: Meson Build
      uses: BSFishy/meson-build@v1.0.3
      with:
        action: build