name: github-actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-20.04
          cuda: "11.3"
          gcc: 10
    env:
      build_dir: "build"
      config: "Release"
    steps:
    - name: Checkout Project
      uses: actions/checkout@v2
    - name: Install Cuda
      env:
        cuda: ${{ matrix.cuda }}
      run: ./scripts/actions/install_cuda_ubuntu.sh
      shell: bash
    - name: Installed Cuda Version
      run: ${{steps.cuda-toolkit.outputs.cuda}}
    - name: Cuda Install Location
      run: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}
    - name: NVCC
      run: nvcc -V
    - name: Install Ninja
      run: pip3 install ninja
    - name: Install Meson
      run: pip3 install meson
    - name: Install cmake/gtest
      run: sudo apt-get install cmake libgtest-dev
    - name: Look at Environment LD_LIBRARY_PATH
      run: echo $LD_LIBRARY_PATH
    - name: CUDA_ROOT
      run: CUDA_ROOT=/usr/local/cuda-11.2/lib64
    - name: Meson Build
      uses: BSFishy/meson-build@v1.0.3
      with:
        action: build

