name: github-actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v2
    - name: cuda-toolkit (Install CUDA)
      uses: Jimver/cuda-toolkit@v0.2.3
    - name: Installed Cuda Version
      run: ${{steps.cuda-toolkit.outputs.cuda}}
    - name: Cuda Install Location
      run: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}
    - name: NVCC
      run: nvcc -V
    - name: Install Ninja
      run: pip3 install ninja
    - name: Install Meson
      run: pip3 install meson
    - name: Install cmake/gtest
      run: sudo apt-get install cmake libgtest-dev
    - name: Look at Environment LD_LIBRARY_PATH
      run: echo $LD_LIBRARY_PATH 
    - name: Meson Build
      uses: BSFishy/meson-build@v1.0.3
      with:
        action: build

